project_id = "kkjamjvtgwpucghixpsv"

[functions.chat]
verify_jwt = false

[functions.sandtray-analysis]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.verify-sms]
verify_jwt = false